### ISSUE TITLE
Javy may not build with WASI SDK 20

### ISSUE THREAD

**Issue by jianghong** [bytecodealliance/javy#323]
## What is the idea?
 wasi-sdk-20 has been released https://github.com/WebAssembly/wasi-sdk/releases/tag/wasi-sdk-20

## What problem does it solve?
we should try to support it

**Comment by surma** [comment]
I don’t think we have tested _building_ javy on Windows. I suspect that is the source of the problem here. Can you try building it from WSL?

**Comment by autobahn883** [comment]
hi @jeffcharles i'd install MinGw and run again still i got have error.
![image](https://user-images.githubusercontent.com/7939278/234903756-10a6dde7-858c-4273-a408-2020ef8421d0.png)

**Comment by autobahn883** [comment]
@surma run it also in ubuntu got many errors.

**Comment by autobahn883** [comment]
hi @jeffcharles i use Ubuntu 22.04 via WSL. this is the error
![image](https://user-images.githubusercontent.com/7939278/235351339-f50efe32-dc8f-4ee9-b850-3836335134eb.png)

**Comment by jeffcharles** [comment]
The error message you're seeing is indicating that `clang` in the WASI SDK is not a valid Linux ELF executable file. Can you confirm that you're using the Linux build and not the Windows build of the WASI SDK?

**Comment by jeffcharles** [comment]
Javy modules import the WASI preview1 APIs so you need to provide implementations for those APIs in your host environment when instantiating the modules or your module will fail to instantiate. If this is running in the browser, as opposed to in Node or Deno, you may be able to use https://github.com/bjorn3/browser_wasi_shim or an alternative to provide implementations for those WASI APIs so your module can be instantiated.

> does javy compatible to http?

It depends on exactly what you mean by _compatible to http_.

There is currently no built-in support for the `fetch` or `XMLHttpRequest` APIs in Javy. One or more callbacks could be added so that support is available. But based on the code you've provided, I don't think the problem you're running into is related to HTTP.

**Comment by surma** [comment]
Fixed in #382
