### ISSUE TITLE
Audit CI to find opportunities to have it finish faster

### ISSUE THREAD

**Issue by jianghong** [bytecodealliance/javy#324]
There may be opportunities to have Javy's CI execute faster on PRs. Doing this means we get faster feedback.

**Comment by jeffcharles** [comment]
- Using Linux instead of MacOS for CI resulted in a ~2x speedup according to https://github.com/jeffcharles/javy/actions/runs/5401996292 (28 minutes on that branch vs 54 minutes in main)

**Comment by ubiquitous-dev** [comment]
Looks like the tests are taking a majority of the CI time.  Is there a way to parallelize wasi tests? or is that already happening, and the overhead of running the tests is just large?  If that's the case, one option would be to shard the tests and have multiple jobs run in parallel using a matrix.

**Comment by jeffcharles** [comment]
> Looks like the tests are taking a majority of the CI time

The step labelled _Tests_ in CI performs a number of distinct operations including compilation. Here's a breakdown of  the timings I'm seeing from [the latest CI run](https://github.com/bytecodealliance/javy/actions/runs/5508808121/jobs/10040599862):

| Step | Time |
| --- | --- |
| Checkout | 46s |
| Restore cargo cache | 30s |
| Restore target cache | 58s |
| Install wasmtime-cli | 1s |
| Install cargo-wasi | 3s |
| Install cargo-hack | 1s |
| Install wizer | 0s |
| Install wasi-sdk | 3s |
| Compile quickjs-wasm-rs | 56s |
| Test quickjs-wasm-rs | 5s |
| Compile javy | 40s |
| `cargo hack wasi test --package=javy-apis --each-feature -- --nocapture` | 16s |
| Compile javy-core for testing | 1s |
| Compile release of javy-core | 56s |
| Wizer javy-core | 1s |
| Compile javy-cli | 17m 8s |
| Test javy-cli | 1m 55s |
| Re-compile javy-cli for WPT (enables promises feature) | 6m 39s |
| WPT | 14s |
| Check benchmarks | 2s |
| Lint | 1m 25s |
| Post target cache | 0s |
| Post cargo cache | 0s |

It looks to me like the compilation of `javy-cli` (and the recompilation for WPT) is what's using the majority of the CI time. I think it makes sense to look focus on ways to reduce that time or parallelize the recompilation for WPT.

Right now, my thinking is rewrite the CI job to use MacOS to compile a release build of `javy-core` and then one Ubuntu job to compile and test `javy-cli` and one Ubuntu job running in parallel to compile and run the WPT tests.

**Comment by jeffcharles** [comment]
I created a branch at https://github.com/jeffcharles/javy/pull/11 to experiment with changing CI to use MacOS to compile and test the core pieces and Ubuntu for everything else. The initial results in https://github.com/jeffcharles/javy/actions/runs/5512822820 look promising.

<img width="741" alt="Screenshot 2023-07-10 at 17 20 02" src="https://github.com/bytecodealliance/javy/assets/154890/e714b292-b62b-44b6-bfbe-99e4690dc420">

The total duration is a little misleading because it took Github 13 minutes to find a MacOS runner after the job was triggered. If that were faster, the job would've finished in 19 m 25 s.

I'm also thinking it may be worth looking into using `lld` or `mold` for linking on Ubuntu instead of the default linker based on https://nnethercote.github.io/perf-book/compile-times.html#linking.

**Comment by jeffcharles** [comment]
For using lld and mold, I used the WPT workflow to judge since we need to use Linux to use those and that offered the best mechanism.

| Linker | CLI compilation time in WPT test | URL |
| --- | --- | --- |
| Default | 16m 15s | https://github.com/bytecodealliance/javy/actions/runs/5547255166/jobs/10128643829 |
| lld | 13m 22s | https://github.com/jeffcharles/javy/actions/runs/5546431787/jobs/10126703575 |
| mold | 19m 09s | https://github.com/jeffcharles/javy/actions/runs/5546749067/jobs/10127450068 |

It looks like switching to lld makes sense if we use Ubuntu to compile the CLI.

**Comment by jeffcharles** [comment]
Merged #460 to compile the CLI on Linux.

Going to close this issue at this point since the Linker change is likely going to be a very minimal benefit compared to other changes.
