### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by amatiasq** [bytecodealliance/javy#381]
Looks like I'm missing something here.

What's the benefit of compiling Javascript to WebAssembly?

After all if a system runs WebAssembly it also runs Javascript directly, isn't it?

**Comment by surma** [comment]
You can read more about why Shopify started Javy here [here](https://shopify.engineering/javascript-in-webassembly-for-shopify-functions).

In general, if you look at Wasm as a universal binary format and/or a strong sandboxing technology, it should become clear why one might want to run JavaScript inside Wasm, rather than running JS directly.

(Additionally, `wasmtime` for example can _only_ run Wasm, not JavaScript.)
