### ISSUE TITLE
Does Javy support FFI?

### ISSUE THREAD

**Issue by zwlaka** [bytecodealliance/javy#408]
I'd like to compile a js that interoperates with c by using the ffi module provided by node.js. Unfortunately, while it can be successfully compiled by Javy, the wasm module can not be executed on wasmtime. Here is my code:

```
const ffi = require('ffi');
const myLibrary = ffi.Library('/root/ffi/js/lib.so', {
    'myfunction': ['int', ['int', 'int']]
  });
const result = myLibrary.myfunction(3, 4);
console.log(result);
```
```
int myfunction(int a, int b) {
    return a+b;
}
```
and the error message generated by wasmtime:
```
Error while running JS: Uncaught ReferenceError: 'require' is not defined
    at <anonymous> (function.mjs:1)

Error: failed to run main module `test.wasm`

Caused by:
    0: failed to invoke command default
    1: error while executing at wasm backtrace:
           0: 0x149ec - <unknown>!<wasm function 204>
           1: 0x13dfe - <unknown>!<wasm function 203>
           2:  0xdf9 - <unknown>!<wasm function 10>
    2: wasm trap: wasm `unreachable` instruction executed
```
Does Javy not support FFI, or did I miss something?

**Comment by jeffcharles** [comment]
> I'd like to compile a js that interoperates with c by using the ffi module provided by node.js

That's not possible. Javy does not provide support for Node.js APIs, it just supports ECMA2020 APIs and a subset of the `TextEncoder`/`TextDecoder` APIs.

Also, for additional context, WebAssembly modules by design cannot link against native libraries. What you can do in Wasm modules is import functions. And at runtime, your Wasm runtime engine can be configured to provide implementations for those imported functions either from hostcalls or a different Wasm instance.

**Comment by jeffcharles** [comment]
You cannot _dynamically_ link against native code (that is, an `.so` file) from a Wasm module 🙂  (I edited my prior comment to clarify).
