### ISSUE TITLE
Unable to build dynamic-linked module with custom imported host function

### ISSUE THREAD

**Issue by ubiquitous-dev** [bytecodealliance/javy#459]
Hello!

I'm trying to build a custom api feature to extend Javy functionality with the ability to call the host with a json payload.  

I am trying to define a method `invoke_json` within the `ubiq_fn` namespace.  However, I want the actual implementation of this to come from a host-provided function, not from rust or js code, so it's not quite like the existing javy API methods, where the functionality is built into the runtime.  It's the host import that I'm struggling with getting working with a dynamic-linked module.

I have [added files to the apis crate](https://github.com/ubiquitousplatform/javy/tree/ubiquitous-functions-support/crates/apis/src/ubiq_fn) and the corresponding Cargo.toml etc, and in that code, I have an [extern statement that references the invoke-json method](https://github.com/ubiquitousplatform/javy/blob/e0b61bb2d246a5001d14a5c04509815a99ee0db2/crates/apis/src/ubiq_fn/mod.rs#L18) that I would like to define within the host.

When I [build javy and cli](https://github.com/ubiquitousplatform/javy/blob/e0b61bb2d246a5001d14a5c04509815a99ee0db2/compile-javy.ps1) and then use the cli with this custom API to then [build my js program normally](https://github.com/ubiquitousplatform/javy/blob/cd784c5012dd080788e3b401582431ace6a3810a/compile-js-example.ps1), everything works fine.  The custom method is [callable from the js program](https://github.com/ubiquitousplatform/javy/blob/cd784c5012dd080788e3b401582431ace6a3810a/javy-example.js#L18) without any issue.

  However, when I use this same build of the custom javy-cli to build this same js code [with -d option specified for the dynamic version](https://github.com/ubiquitousplatform/javy/blob/cd784c5012dd080788e3b401582431ace6a3810a/compile-js-example-dynamic.ps1), I get the error during the cli build (not at runtime - it doesn't even get through the build):
```Error: unknown import: `ubiquitous_functions::invoke_json` has not been defined```.

This seems to be in reference to my external namespace include referenced above.

I'm getting a bit more comfortable with javy, and have instrumented the CLI trying to debug this, but I'm fairly new to rust and am having trouble figuring out exactly where the issue is coming from.  I can see roughly where the CLI is building the rust program and then building it into the quickjs provider wasm file.  I have tried disassembling the `javy_quickjs_provider.wasm` file with `wasm-decompile` and `wasm2wat` and I can see that it has an import for the `invoke_json` method, and I'm thinking this is probably the problem when it tries to run the wasm file for Wizer'ing. It is trying to import a namespace/module during the wizer runtime that's not defined at that point, because that's a wasm runtime that the CLI is setting up on the fly for purposes of wizering and it doesn't have my custom host function registered. 

I'm not clear on how I can fix this though.  I don't really want the wizered version to import that method.  I want the import to end up in the dynamic wasm module, not in the quickjs provider method.  I'm assuming the wizered quickjs provider can't import this because this method doesn't exist.  I have considered stubbing this out in the cli code when it loads up the wasm instance to build the provider, but I'm not sure if that will work.  I think what I really want is some way to add on rust code that's built into the dynamic portion of the assembly where I could put the host function into that section instead, but I'm just not sure where I would do that at.

What I'm trying to accomplish in the grand scheme of things is having a method (either in JS or in Rust, it doesn't matter to me) that I can use to call a host function that's registered into the wasmtime instance that's executing the code, and I want the js runtime to be using the dynamic quickjs provider if possible.

Does anyone have any idea of where I'm going wrong with this?  I can use the non-dynamic one for now, but I'd love to leverage the benefits of the dynamic runtime if possible!

**Comment by jeffcharles** [comment]
I think there's some confusion going on here so I'll try to clarify some things.

>  I get the error during the cli build (not at runtime - it doesn't even get through the build):

This is a little ambiguous to me. Do you mean you get this error while running `cargo build -p javy-cli --release`? Or while running `target/release/javy compile -d [...]`?

> I can see roughly where the CLI is building the rust program and then building it into the quickjs provider wasm file

The CLI does not build the Rust program into the quickjs provider Wasm file. `cargo build -p javy-core` creates `target/wasm32-wasi/release/javy_quickjs_provider.wasm` and `target/wasm32-wasi/release/javy_core.wasm`. Then the CLI's build script (not the CLI itself but rather the part of the crate that runs during `cargo build -p javy-cli`), will wizen the ``target/wasm32-wasi/release/javy_quickjs_provider.wasm` module and output the wizened version into the `OUT_DIR` for the include_bytes! macro that's in the CLI code to consume. But the inclusion of the bytes happens when running `cargo build`.

> I have tried disassembling the javy_quickjs_provider.wasm file with wasm-decompile and wasm2wat and I can see that it has an import for the invoke_json method, and I'm thinking this is probably the problem when it tries to run the wasm file for Wizer'ing.

Yes that's correct. The wizening process instantiates the Wasm module to wizen it and Wasm instantiation will fail if there are imports that are not defined.

> I'm not clear on how I can fix this though.

Broadly speaking, our recommendation is to create your own CLI and equivalent of `javy-core` and have those use the `javy` and `javy-apis` crates we publish. Similar to how with Wasmtime, it's more typical for projects to use the wasmtime crate to build their applications around than it is to use the Wasmtime CLI.

As for specifics, you can define a custom linker for Wizer to use with https://github.com/bytecodealliance/wizer#using-wizer-with-a-custom-linker and define a stubbed implementation. Also keep in mind that the CLI that's in the `javy` repository also instantiates the `javy_quickjs_provider.wasm` to convert the JS source code string to QuickJS bytecode so you'll need to do something similar to provide a stubbed import for that instantiation.

> I want the import to end up in the dynamic wasm module, not in the quickjs provider method. 

You'll _need_ an import for this function in the `javy_quickjs_provider.wasm` module. The reason being, the JS is executing inside the `javy_quickjs_provider` instance, when it invokes a callback in the Rust code, that Rust code is executing inside the same `javy_quickjs_provider` instance, so for that Rust code to call _something_ outside the `javy_quickjs_provider` instance, whether that be the host or code in the dynamic module instance, the `javy_quickjs_provider` needs to import a function to make that outbound call.

> I think what I really want is some way to add on rust code that's built into the dynamic portion of the assembly 

You can change the code in https://github.com/bytecodealliance/javy/blob/ae6f38f21115277f3120f8b561bf4a0237c4a4a1/crates/cli/src/wasm_generator/dynamic.rs to add whatever you need. But, you'll likely need to add the function you are importing as an exported function as well and also import that function on the `javy_quickjs_provider.wasm` file for the Rust code to be able to invoke it.

> I want the js runtime to be using the dynamic quickjs provider if possible.

The runtime runs in the `javy_quickjs_provider.wasm` module when using dynamic linking. It's not possible for the JS code to run in the generated module. All the generated module does is hold the generated QuickJS bytecode in a data segment, copy it into the provider instance's memory, and then invoke an exported function on the provider instance to have the provider instance execute the QuickJS bytecode.

Hopefully this clears a few things up!

**Comment by ubiquitous-dev** [comment]
Thanks so much for the detailed breakdown! That’s extremely helpful. I believe I follow what you’re saying. I’ll give it a try over the weekend and work to realign my mental model of this, and report back if I’m able to get it working!

**Comment by ubiquitous-dev** [comment]
> This is a little ambiguous to me. Do you mean you get this error while running `cargo build -p javy-cli --release`? Or while running `target/release/javy compile -d [...]`?

I get the error during `target/release/javy compile -d [...]`. The cli builds fine. Sorry for the confusion, I was just saying that the import failure was not when executing wasm but when trying to build the wasm from the JS source. There are so many build steps, it’s hard to accurately describe them sometimes!

**Comment by jeffcharles** [comment]
> I get the error during target/release/javy compile -d [...].

Interesting. I'm surprised `cargo build -p javy-cli` worked given that wizens the `javy_quickjs_provider.wasm` module. But yeah, the instantiation in https://github.com/bytecodealliance/javy/blob/ae6f38f21115277f3120f8b561bf4a0237c4a4a1/crates/cli/src/bytecode.rs#L24 will probably also fail if there are non-WASI imports in the `javy_quickjs_provider.wasm` module. You just need to add stubbed versions of any imported functions to the linker.

**Comment by ubiquitous-dev** [comment]
Yeah, I'm not 100% sure why it compiles and wizens but fails when it's used.  I tried doing a cargo clean and removing the link-time-optimization disable flag and rebuilding everything from scratch, just to confirm that I wasn't accidentally using some cached version of the build or disabling LTO caused it to work or something, and it still built successfully.  The commands I'm using for build are:
```cargo build -p javy-core --target=wasm32-wasi -r
cargo build -p javy-cli -r```

Thanks for the pointers, I'll be working on this and will let you know where I get.

**Comment by ubiquitous-dev** [comment]
The pointers to the cli were very helpful since I'm currently using a fork of the javy CLI.  All I needed to do was tell wasmtime to stub the method while it was instantiating the wasm file to generate the quickjs bytecode:
```
    let wasi = WasiCtxBuilder::new().inherit_stderr().build();
    let mut store = Store::new(&engine, wasi);
+   linker.define_unknown_imports_as_default_values(&module);
    let instance = linker.instantiate(&mut store, &module)?;
    let memory = instance.get_memory(&mut store, "memory").unwrap();
```
and it worked perfectly!  Now I've got a dynamic module where the quickjs provider wasm is able to invoke the host function at runtime.  It's a beautiful thing!

Thanks again @jeffcharles  for all the help, much appreciated!
