### ISSUE TITLE
Get wrapped rust value in quickjs-wasm-rs 2.0.1

### ISSUE THREAD

**Issue by ullgren** [bytecodealliance/javy#486]
## What is your question?
First let me confess that I'm a beginner to rust, so I appoligize in advance if this is a newbie question.
 
In version 0.1.4 of the  quickjs-wasm-rs crate it was possible to create a `Value` by wrapping a rust value and then adding callbacks on the property. In this call back one could then use `this.get_rust_value()` to get the wrapped rust value. See example below. 

I'm struggling to migrate this example into newer versions of the crate, such as 2.0.1. It seems that while the `JSContextRef::wrap_rust_value()` function is still present there is no obvious way to get the rust value back from the resulting `JSValueRef`. I've tries using various versions of `try_into` and similar. 

Example that compiles and run as expected with quickjs-wasm-rs 0.1.4

```rust
use quickjs_wasm_rs::Context;

struct SomeData {
    counter: i32,
    message: String,
}

fn main() {
    let context = Context::default();
    let some_data = SomeData {
        counter: 42,
        message: "Hello World!".to_string(),
    };
    let some_data_js_value = context.wrap_rust_value(some_data).unwrap();

    some_data_js_value
        .set_property(
            "increment",
            context
                .wrap_callback(move |ctx, this, _args| {
                    let mut some_data = this.get_rust_value::<SomeData>().unwrap().borrow_mut();
                    some_data.counter += 1;
                    ctx.undefined_value()
                })
                .unwrap(),
        )
        .unwrap();
    some_data_js_value
        .set_property(
            "print",
            context
                .wrap_callback(move |ctx, this, _args| {
                    let some_data = this.get_rust_value::<SomeData>().unwrap().borrow_mut();
                    println!(
                        "Some data: count {} message {}",
                        some_data.counter, some_data.message
                    );
                    ctx.undefined_value()
                })
                .unwrap(),
        )
        .unwrap();
    let global = context.global_object().unwrap();
    global.set_property("somedata", some_data_js_value).unwrap();

    context
        .eval_global("index.js", "somedata.increment(); somedata.print('hello');")
        .unwrap();
}
```

**Comment by saulecabrera** [comment]
Hi @ullgren, `get_rust_value` was indeed removed in newer versions of the crate; nevertheless I believe you could achieve a similar outcome by using `[from_qjs_value](https://github.com/bytecodealliance/javy/blob/main/crates/quickjs-wasm-rs/src/js_value/qjs_convert.rs#L28)`, which converts from `JSValueRef -> JSValue`.

**Comment by ullgren** [comment]
@saulecabrera Thanks for the reply. Unfortunately it helped me but not really there yet :thinking: 

I've found [`get_rust_value`](https://github.com/bytecodealliance/javy/blob/main/crates/quickjs-wasm-rs/src/js_binding/context.rs#L491) that seems to do what I want from a `JSValue`, however it is not a public. Is there any reason for this and is there any other way to grab that internal pointer ?

**Comment by saulecabrera** [comment]
@ullgren After digging a bit more into this, I see the issue that you're facing. Unfortunately we don't support in place modification of JS values at the moment, more concretely, the reason why in newer versions of the crate we no longer expose `get_rust_value` is because we have modified the APIs in such a way that it should be impossible to leak or handout raw pointers, for safety, given that a value should never outlive its context. `get_rust_value`and `wrap_rust_value` (which should be private actually) are only used to deal with closure types, which is an internal detail of the crate. 

I think that there's a path to enabling an API that will allow you modify JS objects in place, but it will require a bit of work: 

One approach could be to create an API at at the `JSValueRef` struct that allows you to modify overwrite the internal value; then you could make use of the already existing [serializers](https://github.com/bytecodealliance/javy/tree/main/crates/quickjs-wasm-rs/src/serialize) to go from `JSValueRef -> T` and `T->JSValueRef` and modify the internal value completely in place:

```rust
.wrap_callback(move |ctx, this, _args| {
    let mut deserializer = Deserializer::from(this);
    let mut my_object = MyObject::deserialize(&mut deserializer);
    // .. do modifications to your object as needed
    let mut serializer = ValueSerializer::from_context(cx)?;
    let v = my_object.serialize(&mut serializer)?;
    this.swap(v) // This is the new API that we could introduce.
    let counter: i32 = this.get_property("counter")?.try_into()?;
    this.set_property("counter", to_qjs_value(ctx, &(counter + 1).into())?);
    Ok(JSValue::Undefined)
}).unwrap();
```


Another simpler approach, would be to explore the use of `JSValueRef::get_property` and `JSValueRef::set_property` to modify the value in place, which might be simpler if you don't have a need to actually convert the value to a Rust struct, something like (NB: I didn't test this)

```rust

.wrap_callback(move |ctx, this, _args| {
    let counter: i32 = this.get_property("counter")?.try_into()?;
    this.set_property("counter", to_qjs_value(ctx, &(counter + 1).into())?);
    Ok(JSValue::Undefined)
}).unwrap();
      
```

**Comment by ullgren** [comment]
@saulecabrera Thanks for looking into this and providing such a detailed answer much appreciated.
I'm certain that we will find a way forward with the example you provided.
