### ISSUE TITLE
Is it works faster then JavaScript?

### ISSUE THREAD

**Issue by coderaiser** [bytecodealliance/javy#487]
I didn’t see any benchmarks, would it work faster then usual JavaScript in V8?

**Comment by saulecabrera** [comment]
The short answer is no, currently WebAssembly doesn't allow dynamic code generation, which is needed for the traditional multi-tier compiler architectures like V8, on top of that QuickJS only offers an interpreter, which will be generally slower than a baseline and/or optimizing compiler. See https://github.com/bytecodealliance/javy/issues/480 for more details.

**Comment by coderaiser** [comment]
Is it possible to use `v8` or other jit compiler instead of Quick JS?

**Comment by saulecabrera** [comment]
It's definitely possible to use another JavaScript engine, but relying on any of the JIT compilers used on those engines is not trivial; it's important to consider that since WebAssembly doesn't allow for dynamic code generation _at runtime_ none of these JIT compilers will work out of the box in the same way that they work on non-Wasm environments. If you're curious about the details, I recommend reading: https://wingolog.org/archives/2022/08/18/just-in-time-code-generation-within-webassembly.

I'll go ahead and close this issue since the main question was already addressed, but feel free to continue the discussion.

**Comment by coderaiser** [comment]
Thanks for a quick response and good article, I just find out there is a library based on SpiderMonkey https://github.com/bytecodealliance/componentize-js, but it looks like it also want be very fast
