### ISSUE TITLE
What is stopping support for `wasm32-unknown-unknown` for `quickjs-wasm-rs`?

### ISSUE THREAD

**Issue by chilipepperhott** [bytecodealliance/javy#489]
## What is your question?

Hey all. I just wanted to say: fantastic project and I'd love to help out in any way I can.

I'm working on a project that requires a JS sandbox in the browser _and_ on the server, both running inside Node.js. 
There, however is one hiccup: the portion of our app that requires access to a JS sandbox is written in Rust, and compiled with `wasm-bindgen` to `wasm-unknown-unknown`.

It seems as though `quickjs-wasm-rs` is the perfect candidate for our use-case, except for the fact that it currently only targets `wasm32-wasi`. Since it is a differant target, I cannot add it to our Rust module.

That is all to say: has compilation of `quickjs-wasm-rs` to `wasm32-unknown-unknown` been attempted by anyone else? What did you learn? I would love to work on adding support, if possible, but I wanted to hear from ya'll first.

**Comment by jeffcharles** [comment]
The summary of what's stopping support is `quickjs-wasm-sys` would need a libc implementation for `wasm32-unknown-unknown` that the QuickJS C code can be statically linked against.

`quickjs-wasm-rs` is built using `quickjs-wasm-sys` and `quickjs-wasm-sys` is built using QuickJS's C code and QuickJS's C code has a number of `#include`s and some of those includes contain code for a number of side-effecting system calls[^1]. These includes mean that compiling QuickJS to a new target requires using an SDK that provides implementations for those includes. Typically on native Linux, that would be provided by 
linking glibc or musl, in a browser, someone could use Emscripten, on a server, we use the WASI SDK. We would like to avoid forking the QuickJS C code we vendor.

For one concrete example of where these system calls can be used, when creating a QuickJS Context with the `JS_NewContext` function, `JS_AddIntrinsicBaseObjects` is called[^2], which calls `js_random_init`[^3], which makes a `gettimeofday` call[^4], and `gettimeofday` is a side-effecting libc system call that needs to have an implementation defined for the target the crate is being compiled for. Since `wasm32-unknown-unknown` doesn't have a clock, there's no implementation defined for that function without something external to the compiler and linker adding one.

[^1]: https://github.com/bytecodealliance/javy/blob/59538f9d2cacb6be5cfd1a192e11b5009e511cc2/crates/quickjs-wasm-sys/quickjs/quickjs.c#L25-L34
[^2]: https://github.com/bytecodealliance/javy/blob/59538f9d2cacb6be5cfd1a192e11b5009e511cc2/crates/quickjs-wasm-sys/quickjs/quickjs.c#L2159
[^3]: https://github.com/bytecodealliance/javy/blob/59538f9d2cacb6be5cfd1a192e11b5009e511cc2/crates/quickjs-wasm-sys/quickjs/quickjs.c#L51034
[^4]: https://github.com/bytecodealliance/javy/blob/59538f9d2cacb6be5cfd1a192e11b5009e511cc2/crates/quickjs-wasm-sys/quickjs/quickjs.c#L41891
