### ISSUE TITLE
Update to latest quickjs?

### ISSUE THREAD

**Issue by Enter-tainer** [bytecodealliance/javy#569]
## What is your question?

Quickjs just launch a new version days ago https://github.com/bellard/quickjs/commit/daa35bc1e5d43192098af9b51caeb4f18f73f9f9 , it contains some bug fixes. Maybe we can update quickjs-wasm-rs to the latest qjs

**Comment by jeffcharles** [comment]
Because Javy supports generating dynamically linked Wasm modules, I need to evaluate the forwards and backwards compatibility between the QuickJS bytecode generated by the 2023-12-09 release and the 2021-03-27 release. If the bytecode has not changed, we can make the update. If the bytecode format has changed, we'll need to make a staged wider update to the codebase to ensure we don't break existing deployments of dynamically linked Javy Wasm modules.

For additional context, it's very unlikely I'll have time to address this before January given I'll be taking vacation this month and other commitments. But this is something I will be looking at.

**Comment by Enter-tainer** [comment]
thanks for your reply!

**Comment by jeffcharles** [comment]
`quickjs-wasm-sys` version 1.2.0, `quickjs-wasm-rs` version 3.0.0, `javy` version 2.2.0, and `javy-apis` version 2.2.0 should all now be updated to use release `2023-12-09` of QuickJS. We're planning to update to the `2024-01-13` release of QuickJS at some point in the future.
