### ISSUE TITLE
Is it possible to compile a wasm file that can be executed in HTML?

### ISSUE THREAD

**Issue by akang1937** [bytecodealliance/javy#827]
When I compiled the file, I got two kinds of error messages like this: 
1. TypeError: WebAssembly.instantiate(): Import #0 "wasi_snapshot_preview1": module is not an object or function
2. TypeofError: WebAssembly.instantiate(): Imports argument must be present and must be an object

Is there a way to generate a wasm file that works fine directly in the browser. I just need to run it in the browser.

**Comment by saulecabrera** [comment]
Can you share the file that you're trying to compile and how you're trying to load the compiled file from JavaScript?

In general javy-generated binaries are WASI compliant, so in order to run them in the browser, I'd recommend using a WASI shim, e.g., https://github.com/bjorn3/browser_wasi_shim. You could try setting up your environment following the [example in the README](https://github.com/bjorn3/browser_wasi_shim?tab=readme-ov-file#usage).

**Comment by saulecabrera** [comment]
> but it doesn't seem to work in pure HTML.

Could you expand what you mean by this? If you'd like to integrate your module's behaviour with an HTML page, one way is to make use of the DOM APIs, to manipulate the DOM. Note that Javy doesn't provide any DOM APIs though; which means that if you'd like to go this route, you'd probably need to create your own bindings to those APIs.An alternative to this approach would be to use [wasm-bindgen](https://github.com/rustwasm/wasm-bindgen).

> Also, using Javy to compile JavaScript to Wasm can greatly improve performance? 

It depends what kind of payload of program you're trying to run, in general Javy embeds a QuickJS interpreter, which works on top of QuickJS bytecode. I'd recommend running some benchmarks to better understand if Javy-generated modules meet your needs performance-wise.

**Comment by saulecabrera** [comment]
Your errors suggest that your module can't instantiate due to missing imports, likely the WASI ones. 

To work with  the `browser_wasi_shim`, you most likely need to install it via npm and bundle your JS into a single source (with a JS bundler like webpack https://webpack.js.org/). Once bundled, you can then proceed to include the bundled JS in your HTML script tag.

**Comment by saulecabrera** [comment]
You can take a look the [examples](https://github.com/bjorn3/browser_wasi_shim/blob/main/examples/rustc.html#L31) for inspiration.
